### ISSUE TITLE
Fix missing periods "." in timelines

### ISSUE THREAD

**Issue by ImmanuelXIV** [hyper-scale/frontend#52]
In the timelines in the sections "Shareholder review" and "Funding" there are "."s missing.

web app
![timeline-lg](https://user-images.githubusercontent.com/12730135/145684907-ffe372d4-a4ba-4ec7-a8ab-605d18485de1.png)

mobile
![timeline-sm](https://user-images.githubusercontent.com/12730135/145684978-1e860a29-f1d2-44fc-9488-8a98972d8249.png)

**Comment by ClaireBookworm** [comment]
@ImmanuelXIV made a PR
